### ISSUE TITLE
style.css

### ISSUE THREAD

**Issue by TigerClaw33** [FlorianBrinkmann/Bornholm-Artikelreihe#4]
Hi, ich habe eine Frage und zwar habe ich bei allen Themes ein Problem: Wenn ich die style.css öffne und z.B. etwas anpassen oder hinzufügen möchte wie 

body {
    background-color: lightblue;
}

dann hat es absolut keine Wirkung. child-Themen oder zusätzliches CSS funktioniert. Aber wenn ich die Original style.css bearbeiten möchte, hat es keine Wirkung. Kann mir jemand sagen wieso? Denn bei anderen im Internet scheint das zu funktionieren.

**Comment by florianbrinkmann** [comment]
Hi,

hast du das Problem mit dem Bornholm-Theme? Falls nicht, wäre deine Frage hier besser aufgehoben :) https://de.wordpress.org/support/ 
Falls mit Bornholm: wie genau gehst du denn vor, um die Änderung zu machen?

Viele Grüße
Florian

**Comment by TigerClaw33** [comment]
Hi, ich lade dein Theme, gehe auf Design/Editor und wähle die "style.css"-Datei aus. Wenn ich dort dann einen Code platziere, erhalte ich keine Ergebnisse. Wenn ich im css-Verzeichnis z.B. die bornholm.css ändere, funktioniert alles einwandfrei. Verstehe das nur nicht, wieso es keine Wirkung hat, wenn die style.css bearbeitet wird. Auf allen Portalen wird erwähnt, dass die style.css bearbeitet werden kann, aber das hat bei mir bei keinem Theme eine Auswirkung

**Comment by florianbrinkmann** [comment]
Hey,

die style.css wird von Bornholm nicht im Frontend eingebunden, sondern nur die bornholm.css, ich nutze die style.css nur für die notwendigen Metadaten, damit WordPress das Theme erkennt.

Viele Grüße
Florian

**Comment by TigerClaw33** [comment]
Ah ok. Kannst du mir trotzdem sagen, warum andere Themes die style.css mit einigem Programmcode anbieten, man aber keine Änderung wirksam bekommt?

**Comment by florianbrinkmann** [comment]
So pauschal nicht, nein. Die einzigen Möglichkeiten, die mir dazu einfallen:

1. Trotzdem da CSS drin steht, wird die Datei im Frontend nicht geladen.
2. Die Änderunge wird dir nicht angezeigt, weil die style.css noch im Cache ist.
3. Die Änderungen werden von irgendwelchen nachfolgenden Regeln überschrieben.
